# Generated by Django 6.1.1 on 2026-09-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('SUV', 'SUV'), ('Van', 'Van'), ('Truck', 'Truck')], max_length=20)),
                ('problem_level', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.service')),
            ],
        ),
    ]
